version: "3.8"

services:

  flask:
    container_name: flask-uwsgi
    build: ./flask
    volumes:
      - ./web_memo_socks/:/tmp/
    tty: true

  nginx:
    container_name: nginx
    image: nginx:1.23
    volumes:
      - ./web_memo_socks/:/tmp/
      - type: bind
        source: "./nginx/my_server.conf"
        target: "/etc/nginx/conf.d/default.conf"
    ports:
      - 80:80
      - 443:443

volumes:
  web_memo_socks:
